name: demo-provisioning-status
description: Updates the status of a demo deployment
author: Peter Murray

inputs:
  github_token:
    description: GitHub access token
    default: ${{ github.token }}
    required: true

  id:
    description: The id of the demo deployment

  name:
    description: The name of the demo deployment

  actions_run_id:
    description: The run id for the actions workflow
    default: ${{ github.run_id }}
    required: true

  status:
    description: The workflow status, 'success', 'failed' or 'cancelled'
    required: true

runs:
  using: node20
  main: '../dist/demo-provisioning-status/index.js'