name: get-demo-definition
description: Fetches the demo definition from a deployment
author: 'Peter Murray'

inputs:
  github_token:
    description: The GitHub token to use to validate the provided data
    default: ${{ github.token }}

  deployment_id:
    description: The deployment id to get the definition for
    required: true

outputs:
  demo_deployment_id:
    description: The ID for the deployment that contains the demo metadata and lifecycle.

  communication_issue_number:
    description: The optional issue number that is tracking the deployment lifecycle.

  demo_deployment_uuid:
    description: The UUID for the demo deployment.

  demo_deployment_payload:
    description: The JSON payload (in string encoded form) used to create the demo and resources.

runs:
  using: node20
  main: '../dist/get-demo-definition/index.js'
