name: update-issue-labels-action
description: Updates, adding/removing the specified labels from an issue or pull request.
author: Peter Murray

inputs:
  github_token:
    description: GitHub access token
    default: ${{ github.token }}
    required: true

  labels_to_add:
    description: The labels to add, separated by a comma if there are multiple entries.

  labels_to_remove:
    description: The labels to remove, separated by a comma if there are multiple entries.

  repo:
    description: The owner and repository name. e.g. octodemo/bookstore, defaults to the current repository if not specified.
    required: false

  issue_number:
    description: The number of the issue or pull request, which will default to extracting from the workflow event if not specified.
    required: false

branding:
  icon: bookmark
  color: blue

runs:
  using: node20
  main: '../dist/update-issue-labels/index.js'