name: demo-lifecycle-status
description: Updates the lifecycle status of a demo deployment
author: Peter Murray

inputs:
  github_token:
    description: GitHub access token
    default: ${{ github.token }}
    required: true

  id:
    description: The id of the demo deployment
    required: true

  actions_run_id:
    description: The run id for the actions workflow
    default: ${{ github.run_id }}
    required: true

  lifecycle_status:
    description: The demo lifecycle status, 'hold', 'warning', 'terminate', 'unhold'.
    required: true

runs:
  using: node20
  main: '../dist/demo-lifecycle-status/index.js'